version: "3.8"

services:
  gdino:
    image: my-gdino
    container_name: gdino
    gpus: all
    shm_size: "8g"
    devices:
      - /dev/video0:/dev/video0
      - /dev/video1:/dev/video1
    privileged: true
    device_cgroup_rules:
      - 'c 81:* rmw'
    group_add:
      - video
    volumes:
      - ${HOME}/GroundingDINO:/opt/program/GroundingDINO
    command: ["tail", "-f", "/dev/null"]
    restart: unless-stopped
    environment:
      NVIDIA_VISIBLE_DEVICES: "all"
      NVIDIA_DRIVER_CAPABILITIES: "compute,utility,video"
