version: "3.8"

services:
  inference:
    # 상위에서 하위(inference) 폴더의 Dockerfile로 빌드
    build:
      context: .
      dockerfile: inference/Dockerfile
    image: gdino-server:inference
    container_name: gdino-infer
    gpus: all
    shm_size: "8g"
    ports:
      - "8000:8000"
    environment:
      NVIDIA_VISIBLE_DEVICES: "all"
      NVIDIA_DRIVER_CAPABILITIES: "compute,utility"
    # ⬇️ 개발 편의용 볼륨 마운트 (원하는 것만 켜세요)
    volumes:
      # 코드 핫리로드용: app.py만 덮어쓰기 (또는 전체 폴더 마운트)
      - ./:/opt/program/GroundingDINO/
    restart: unless-stopped
    # Dockerfile에서 uvicorn CMD를 이미 설정했다면 이 줄은 생략 가능
